### ISSUE TITLE
Wall time exceeded on cnvkit.sh script

### ISSUE THREAD

**Issue by smrey** [AWGL/SomaticEnrichment#12]
Script cnvkit.sh exceeded walltime- walltime should be increased for this script.

**Comment by erikwaskiewicz** [comment]
As a quick fix, I've made a patch script for re-queueing from this step if it happens again, it's at `/data/results/191108_NB551319_0036_AHNKGTAFXY/RochePanCancer/19M17503/patch.sh`. 

- Copy patch script into the folder that the script failed in (usually the last non-NTC sample)
- Change the variables at the top of the script
- `qsub` within the folder that the script failed

This will redo all of the `CNVKit.sh` bits if they've already been done, but it's quick and doesn't throw an error if it overwrites any of them

**Comment by smrey** [comment]
Called SE_patch.sh and in /data/diagnostics/scripts/

**Comment by mbyvcm** [comment]
I have increased the wall time, but I think that the CNV polling need a rethink. I'll open a new issue for this. #16
