### ISSUE TITLE
add sex check to QC report

### ISSUE THREAD

**Issue by mbyvcm** [AWGL/SomaticEnrichment#6]

**Comment by erikwaskiewicz** [comment]
- Error when sex check was performed, could not find CNVkit output containing sex becuase CNVkit is the last tool to run

- Need to nest combineQcReport.sh into the loop containing the CNVkit scripts

**Comment by cwmedway** [comment]
sex check removed

**Comment by cwmedway** [comment]
sex check removed from next release
